#!/bin/sh
set -eu

go -C pbf2geojson test -mod=readonly ./...
go -C osm2geojson/osm2geojson test -mod=readonly ./...
go -C wikipedia2geojson test -mod=readonly ./...
go -C wikipedia2doc2vec test -mod=readonly ./...
go -C geojson2entirety test -mod=readonly ./...

node --check pbf2geojson/index.js
node --check pbf2geojson/lib/generateParams.js
node --check pbf2geojson/test/end-to-end.js
node --check pbf2geojson/test/lib/generateParams.js
sh -n pbf2geojson/test/pretest.sh
